name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # This matches the folder created in package.json

      - name: Deploy
        uses: actions/deploy-pages@v4
